version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: "python:3.6-slim"
        auth:
          # username: mydockerhub-user
          # password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python manage.py test
          name: Test
  echo-hello-world:
    executor: python/default
    steps:
      - run:
          command: |
            echo Running test
            set +e
            mkdir -p /tmp/test-results
          name: Just-For-Fun

workflows:
  main:
    jobs:
      - build-and-test
      - echo-hello-world
